app:
  baseUrl: http://backstage.localhost:8080

backend:
  baseUrl: http://backstage.localhost:8080
  listen: ':7007'
  cors:
    origin: http://backstage.localhost:8080
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: raw.githubusercontent.com
      - host: github.com
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true

integrations:
  github:
    - host: github.com

catalog:
  locations:
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-resource/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-property/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-sensor/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-actuator/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-system/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-platform/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-deployment/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-simulation/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-catalog/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-dataset/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-distribution/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-dataservice/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-datasetseries/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-operator-activity/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-library-common/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-library-operator-common/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/dynamic-systems-io/component-service-simulation/main/catalog-info.yaml
