apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: system-development-backstage
  description: Custom Backstage application source and image build for development-system.
  tags:
    - backstage
    - developer-portal
    - platform
  annotations:
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: development-system-backstage
    argocd/app-namespace: argocd
    backstage.io/kubernetes-id: development-system-backstage
spec:
  type: service
  owner: group:default/simulation-platform
  lifecycle: experimental
  system: practical-distributed-simulation-platform
